version: '3.5'

networks:
  internal:
    name: internal
    driver: bridge

services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Etc/UTC #optional
      - SUBDOMAINS=${DUCK_DNS_DOMAIN}
      - TOKEN=${DUCK_DNS_TOKEN}
      - LOG_FILE=false #optional
    volumes:
      - ./duckdns/config:/config #optional
    restart: unless-stopped

  webtop:
    image: lscr.io/linuxserver/webtop
    container_name: webtop
    privileged: true #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./webtop:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
    networks:
      - internal

  caddy:
    image: caddy
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN_NAME:${DUCK_DNS_DOMAIN}.duckdns.org
      - CADDY_USER=${CADDY_USER}
      - CADDY_PASSWORD=${CADDY_PASSWORD}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
    networks:
      - internal
    restart: always

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    networks:
      - internal
    restart: always
