version: '3.5'

networks:
  internal:
    name: internal
    driver: bridge

  dynamic-caddy:
    ipam:
      driver: default
      config:
        - subnet: 10.64.32.0/24
          gateway: 10.64.32.1

services:
  duckdns:
    profiles: [ all ]
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Etc/UTC #optional
      - SUBDOMAINS=${DUCK_DNS_DOMAIN}
      - TOKEN=${DUCK_DNS_TOKEN}
      - LOG_FILE=false #optional
    volumes:
      - ./duckdns/config:/config #optional
    restart: unless-stopped

  caddy:
    profiles: [ all ]
    image: caddy
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN_NAME=${DUCK_DNS_DOMAIN}.duckdns.org
      - CADDY_USER=${CADDY_USER}
      - CADDY_PASSWORD=${CADDY_PASSWORD}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
    depends_on:
      - docker-dynamic-caddy
      - duckdns
    networks:
      - internal
      - dynamic-caddy

  docker-dynamic-caddy:
    profiles: [ all ]
    container_name: docker-dynamic-caddy
    image: mheys1/docker-dynamic-caddy
    restart: always
    labels:
      - caddy.dynamic.docker.dns=caddy.${DUCK_DNS_DOMAIN}.duckdns.org
      - caddy.dynamic.docker.target=docker-dynamic-caddy:5000
    volumes:
      - ./docker-dynamic-caddy/data:/app/data
      - ./docker-dynamic-caddy/logs:/app/logs
      - ./docker-dynamic-caddy/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      dynamic-caddy:
        ipv4_address: 10.64.32.254

  portainer:
    profiles: [ all, portainer ]
    container_name: portainer
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    depends_on:
      - caddy
    networks:
      - internal
    restart: always

  webtop:
    profiles: [ all, webtop]
    image: lscr.io/linuxserver/webtop
    container_name: webtop
    privileged: true #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    labels:
      - caddy.dynamic.docker.dns=webtop.${DUCK_DNS_DOMAIN}.duckdns.org
      - caddy.dynamic.docker.target=webtop:3000
    volumes:
      - ./webtop:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    depends_on:
      - caddy
    shm_size: "1gb" #optional
    restart: unless-stopped
    networks:
      - internal

  nodered:
    profiles: [ all, nodered ]
    container_name: nodered
    image: nodered/node-red:1.3.5
    volumes:
      - ./nodered:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - caddy.dynamic.docker.dns=nodered.${DUCK_DNS_DOMAIN}.duckdns.org
      - caddy.dynamic.docker.target=nodered:1880
    environment:
      - TZ=Europe/London
    networks:
      - internal
    restart: unless-stopped

  dozzle:
    profiles: [ all, dozzle]
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - caddy.dynamic.docker.dns=dozzle.${DUCK_DNS_DOMAIN}.duckdns.org
      - caddy.dynamic.docker.target=dozzle:8080

