default_redirection_url: https://www.google.com

server:
  host: 0.0.0.0
  port: 9091

log:
  level: info

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users.yml
    watch: false
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

session:
  name: authelia_session
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  remember_me_duration: 1M

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 120

storage:
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: false
